### ISSUE TITLE
Sort out commit history in myco and fire branches

### ISSUE THREAD

**Issue by dmcglinn** [Fireandplants/plant_gbif#25]
Hey @dschwilk I need your help sorting out what's going on in the commit history of the fire and myco branches. It appears that all of the recent commits you made only appear on one branch. To see this I compared the branches using the PR options. I'm not sure why this happened because I thought your commits where on both branches yesterday. I did just push some commits to try to bring fire up-to-date with changes in myco and maybe I overwrote your commits somehow in the process. Thanks in advance I know this is tedious stuff.

**Comment by dschwilk** [comment]
I've tried to move any general commits to master and only keep project specific code in each of the other two.  But I'll check.

**Comment by dschwilk** [comment]
All those merge commits make things a bit tricky to see.  Advantage of allowing fast-forwards would be a cleaner history but then less record of the actual merge occasions.

**Comment by dschwilk** [comment]
I'm not sure I see a problem.  Only issue I see is that there are now commits that really should be in master that are only on both of the other two branches.  I ahte cherry-picking but we may have to do that since after that huge set of merges you committed it seems that non-specific changes and changes meant for master are all combined.  Best would have been to separate those out and move the generic changes into master first.

**Comment by dmcglinn** [comment]
ugh I'm sorry I messed this up - this is why I need to stick to submitting PRs

**Comment by dmcglinn** [comment]
Once all this is up-to-date I'll refork so that I can do that in the future

**Comment by dmcglinn** [comment]
So I guess the better thing to have to done would have been to move those three commits I wanted on the fire branch first into master and then merged master into fire?

**Comment by dschwilk** [comment]
No worries, we have kind of a weird workflow here.  We can just cherry-pick the geog_filter stuff into master.  We are not working with tightly coupled branches since they are expected to diverge, we can just cherry-pcik back general fixes into master.

Let's get a list of what we need.  Is this correct and complete?

```
e89927a | | | * Remove unnecesary assignment in geog_filter.R
4fca9e2 | | | * Add date to output files.
6a71b29 | | | * Export readr library to cluster

ed894a2 | * | Update field names to accomodate GBIF change
c77184d | * | change name of GBIF input file to accomodate query on 2015
fd94d14 | * | Drop row limit on data import for climate summary
```

Any others?

**Comment by dschwilk** [comment]
To answer your question: yes.  But that is my fault too!  I should have said to do that. That would also have prevented any myco-specific stuff getting into the fire project branch but that possible bad outcome did not happen because of the order of commits anyway).

**Comment by dschwilk** [comment]
No need for separate fork.  Anything you can do in a fork you can do with branches.

**Comment by dschwilk** [comment]
Another option to cherry-picking: we could merge the fire project branch into master.  Any problem with that?  That is the one seeing current work and we have the myco branch set aside as a record and we can tag and release it.  What do you think?

**Comment by dmcglinn** [comment]
Yes all those commits look correct they can go into master and fire branches

**Comment by dschwilk** [comment]
OK, fire-ecol-project rbanch looks correct.  I will simply merge that into master.  Master will no represent work on the fire evolution project.  I can always "generify" it at a later date.

Also note: the fire project is using an older gbif download.  I really should re-download and run all that stuff again if we are going to re-filter anyway. DO NOT USE the myc project extraction since that is specific to the myco species list not the `tanknames` list.

**Comment by dschwilk** [comment]
Done. fire-evol-project merged into master and that has been pushed to origin.

**Comment by dmcglinn** [comment]
Thanks for the help @dschwilk ! @SallyArchibald does want me to re-filter the fire stuff so maybe we should go ahead and update the gbif. I'm also fine just working with the old data dumb and updating when were closer to submission of a manuscript.
